// import 'package:grocery_app/data/models/product_model.dart';
// import 'package:grocery_app/upload_test/upload.dart';

// List<ProductModel> productsUpload = [
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[0]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[1]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[2]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[3]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[4]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[5]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[6]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[7]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[8]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[9]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[10]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[11]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[12]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[13]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[14]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[15]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[16]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[17]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[18]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[19]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[20]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[21]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[22]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[23]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[24]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[25]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[26]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[27]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[28]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[29]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[30]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[31]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[32]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[0]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[1]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[2]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[3]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[4]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[5]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[6]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[7]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[8]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[9]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[10]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[11]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[12]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[13]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[14]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[15]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[16]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[17]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[18]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[19]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[20]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[21]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[22]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[23]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[24]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[25]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[26]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[27]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[28]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[29]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[30]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[31]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[32]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[0]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[1]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[2]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[3]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[4]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[5]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[6]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[7]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[8]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[9]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[10]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[11]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[12]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[13]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[14]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[15]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[16]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[17]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[18]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[19]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[20]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[21]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[22]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[23]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[24]),
//   ProductModel(
//       title: "product 1",
//       price: 769.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[4],
//       images: imagesProducts[25]),
//   ProductModel(
//       title: "product 1",
//       price: 65.3,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[5],
//       images: imagesProducts[26]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[27]),
//   ProductModel(
//       title: "product 1",
//       price: 256,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[6],
//       images: imagesProducts[28]),
//   ProductModel(
//       title: "product 1",
//       price: 24.5,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[0],
//       images: imagesProducts[29]),
//   ProductModel(
//       title: "product 1",
//       price: 100,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[1],
//       images: imagesProducts[30]),
//   ProductModel(
//       title: "product 1",
//       price: 535,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[2],
//       images: imagesProducts[31]),
//   ProductModel(
//       title: "product 1",
//       price: 7854.8,
//       description: dec,
//       quantity: "piece",
//       categoryId: categoryIdList[3],
//       images: imagesProducts[32]),
// ];

// List<List<ImageProduct>> imagesProducts = [
//   [
//     ImageProduct(imgUrl: imagesUrls[0], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[1], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[2], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[3], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[4], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[5], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[6], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[7], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[8], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[9], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[10], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[11], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[12], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[13], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[14], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[15], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[16], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[17], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[18], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[19], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[20], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[21], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[22], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[23], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[24], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[25], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[26], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[27], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[28], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[29], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[30], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[31], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[32], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[0], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[1], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[2], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[3], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[4], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[5], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[6], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[7], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[8], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[9], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[10], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[11], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[12], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[13], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[14], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[15], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[16], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[17], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[18], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[19], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[20], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[21], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[22], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[23], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[24], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[25], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[26], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[27], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[28], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[29], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[30], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[31], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[32], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[0], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[1], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[2], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[3], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[4], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[5], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[6], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[7], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[8], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[9], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[10], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[11], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[12], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[13], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[14], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[15], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[16], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[17], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[18], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[19], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[20], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[21], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[22], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[23], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[24], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[25], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[26], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[27], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[28], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[29], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[30], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[31], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[32], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[0], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[1], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[2], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[3], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[4], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[5], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[6], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[7], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[8], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[9], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[10], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[11], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[12], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[13], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[14], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[15], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[16], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[17], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[18], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[19], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[20], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[21], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[22], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[23], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[24], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[25], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[26], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[27], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[28], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[29], isDefault: false, isSvg: false),
//   ],
//   [
//     ImageProduct(imgUrl: imagesUrls[30], isDefault: true, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[31], isDefault: false, isSvg: false),
//     ImageProduct(imgUrl: imagesUrls[32], isDefault: false, isSvg: false),
//   ],
// ];
